// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'WEBapiKey',
    appId: '1:753588309269:web:cb03308314753afd886d1c',
    messagingSenderId: '753588309269',
    projectId: 'dart-counter-6bf03',
    authDomain: 'dart-counter-6bf03.firebaseapp.com',
    storageBucket: 'dart-counter-6bf03.appspot.com',
    measurementId: 'G-GET0JS93YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ANDROIDapiKey',
    appId: '1:753588309269:android:c7d98ed1e29d6da5886d1c',
    messagingSenderId: '753588309269',
    projectId: 'dart-counter-6bf03',
    storageBucket: 'dart-counter-6bf03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IOSapiKey',
    appId: '1:753588309269:ios:d04a4fab7b924acc886d1c',
    messagingSenderId: '753588309269',
    projectId: 'dart-counter-6bf03',
    storageBucket: 'dart-counter-6bf03.appspot.com',
    iosClientId: '753588309269-4bi8qu9lvcc61aaca6g1mv9h49f0qcgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartboard',
  );
}
